### ISSUE TITLE
move-to-next-monitor always maximizes the window

### ISSUE THREAD

**Issue by thejoshwolfe** [jc00ke/bin#1]
sorry to bother you, but many google search results point to this repository to solve the problem that your `move-to-next-monitor` solves.

the problem seems to be that `xprop -id $(xdotool getactivewindow) _NET_WM_STATE` always includes the property `_NET_WM_STATE_FOCUSED`, but your tool seems to expect that only `_NET_WM_STATE_MAXIMIZED_HORZ` and `_NET_WM_STATE_MAXIMIZED_VERT` could be listed.

I'm on xubuntu 16.04.

I'm currently porting the script to python and making it work the way i want in addition to this fix, so no pressure from me to get this issue addressed. Just wanted to let you and anyone finding this repo in a search know about this issue.

**Comment by jc00ke** [comment]
Hmm, I vaguely remember that I maximized the window because if I didn't the size on the destination monitor would be all messed up.

Also, I assume `xprop` and `xdotool` have changed since I first cobbled this together. And, I've switched to Ubuntu so I don't have a way to debug it anyway.

Thanks for letting me know, maybe it'll help someone else too.

**Comment by jc00ke** [comment]
Even though I don't really have a way to support it, I think a repo on its own it the best thing, so here it is!
https://github.com/jc00ke/move-to-next-monitor

**Comment by anuppuranik** [comment]
I have a pull request on that other repo waiting on you to merge. If you do end up merging, it will be great if you cherry-pick the changes into this one... because links to the script in _this_ repo have gone much too far.

**Comment by jc00ke** [comment]
@anuppuranik thanks for the PR! I merged jc00ke/move-to-next-monitor#1 but I won't be cherry-picking to this repo. This repo is my personal scripts and `move-to-next-monitor` has grown beyond just me :wink:
